### ISSUE TITLE
Importer: error while creating layers

### ISSUE THREAD

**Issue by fb71** [moovida/hydrologis4polymap#4]
Error while creating new layers for imported DB. Seems to be a concurrency issue.

java.lang.IllegalStateException: Error while initializing.
at org.polymap.model2.engine.UnitOfWorkImpl.createEntity(UnitOfWorkImpl.java:173)
at org.polymap.core.project.ops.NewLayerOperation.doWithCommit(NewLayerOperation.java:81)
at org.polymap.p4.layer.NewLayerOperation.doWithCommit(NewLayerOperation.java:128)
at org.polymap.core.project.ops.TwoPhaseCommitOperation.doExecute(TwoPhaseCommitOperation.java:78)
at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:67)
at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:55)
at org.polymap.core.operation.DefaultOperation.execute(DefaultOperation.java:67)
at org.polymap.core.operation.LogOperationConcernFactory$1.execute(LogOperationConcernFactory.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.polymap.core.operation.OperationExecutor.invoke(OperationExecutor.java:113)
at com.sun.proxy.$Proxy40.execute(Unknown Source)
at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:513)
at org.polymap.core.operation.OperationSupport$5.run(OperationSupport.java:271)
at org.polymap.core.operation.OperationSupport$OperationJob.runWithException(OperationSupport.java:340)
at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:225)
at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
at org.polymap.core.runtime.UIJob.run(UIJob.java:221)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalStateException: orderKey already seen:
ILayer[id=ILayer.1828271359,status=CREATED,state=LuceneRecordState[identity=ILayer.1828271359,
    _type_=org.polymap.core.project.ILayer,
    label=Media Notes,
    resourceIdentifier=fe4cf389-c445-4142-ad30-e76255589b47|Media Notes,
    styleIdentifier=FeatureStyle.1828271356,
    parentMap=root,
    ]]
at org.polymap.core.project.ILayer.orderedLayers(ILayer.java:169)
at org.polymap.core.project.ILayer.maxOrderKey(ILayer.java:151)
at org.polymap.core.project.ops.NewLayerOperation.lambda$0(NewLayerOperation.java:88)
at org.polymap.model2.engine.UnitOfWorkImpl.createEntity(UnitOfWorkImpl.java:168)
... 23 more
java.lang.IllegalStateException: Error while initializing.
at org.polymap.model2.engine.UnitOfWorkImpl.createEntity(UnitOfWorkImpl.java:173)
at org.polymap.core.project.ops.NewLayerOperation.doWithCommit(NewLayerOperation.java:81)
at org.polymap.p4.layer.NewLayerOperation.doWithCommit(NewLayerOperation.java:128)
at org.polymap.core.project.ops.TwoPhaseCommitOperation.doExecute(TwoPhaseCommitOperation.java:78)
at org.polymap.core.operation.DefaultOperation.lambda$0(DefaultOperation.java:67)
at org.polymap.core.operation.DefaultOperation.handleException(DefaultOperation.java:55)
at org.polymap.core.operation.DefaultOperation.execute(DefaultOperation.java:67)
at org.polymap.core.operation.LogOperationConcernFactory$1.execute(LogOperationConcernFactory.java:46)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:497)
at org.polymap.core.operation.OperationExecutor.invoke(OperationExecutor.java:113)
at com.sun.proxy.$Proxy40.execute(Unknown Source)
at org.eclipse.core.commands.operations.DefaultOperationHistory.execute(DefaultOperationHistory.java:513)
at org.polymap.core.operation.OperationSupport$5.run(OperationSupport.java:271)
at org.polymap.core.operation.OperationSupport$OperationJob.runWithException(OperationSupport.java:340)
at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:225)
at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:67)
at org.eclipse.rap.rwt.internal.lifecycle.ContextUtil.runNonUIThreadWithFakeContext(ContextUtil.java:41)
at org.eclipse.rap.rwt.lifecycle.UICallBack.runNonUIThreadWithFakeContext(UICallBack.java:54)
at org.polymap.core.runtime.session.RapSessionContextProvider$RapSessionContext.execute(RapSessionContextProvider.java:132)
at org.polymap.core.runtime.UIJob.run(UIJob.java:221)
at org.eclipse.core.internal.jobs.Worker.run(Worker.java:54)
Caused by: java.lang.IllegalStateException: orderKey already seen:
ILayer[id=ILayer.1828271359,status=CREATED,state=LuceneRecordState[identity=ILayer.1828271359,
    _type_=org.polymap.core.project.ILayer,
    label=Media Notes,
    resourceIdentifier=fe4cf389-c445-4142-ad30-e76255589b47|Media Notes,
    styleIdentifier=FeatureStyle.1828271356,
    parentMap=root,
    ]]
at org.polymap.core.project.ILayer.orderedLayers(ILayer.java:169)
at org.polymap.core.project.ILayer.maxOrderKey(ILayer.java:151)
at org.polymap.core.project.ops.NewLayerOperation.lambda$0(NewLayerOperation.java:88)
at org.polymap.model2.engine.UnitOfWorkImpl.createEntity(UnitOfWorkImpl.java:168)
... 23 more
[WARN]  TwoPhaseCommit

**Comment by fb71** [comment]
Fixed in polymap4-core and polymap4-p4.
