### ISSUE TITLE
Kann keine zweite Datenbank laden

### ISSUE THREAD

**Issue by moovida** [moovida/hydrologis4polymap#8]
Um es nicht zu vergessen :-)

/** FIXME dirty hack to get the db instance to FeaturePanelContribution. */
    public static SqliteDb globalDb;
 nicht funkt. Kann keine zweite Datenbank laden

 java.lang.RuntimeException: java.util.concurrent.ExecutionException: java.lang.AssertionError
 at org.polymap.core.catalog.ui.MetadataContentProvider$2.runWithException(MetadataContentProvider.java:207)
 at org.polymap.core.runtime.UIJob.lambda$0(UIJob.java:226)
 at [...]java.util.concurrent.CompletableFuture.reportGet(CompletableFuture.java:357)
 at java.util.concurrent.CompletableFuture.get(CompletableFuture.java:1895)
 at org.polymap.p4.catalog.AllResolver.resolve(AllResolver.java:213)
 at org.polymap.core.catalog.ui.MetadataContentProvider$2.runWithException(MetadataContentProvider.java:199)
 ... 7 more
Caused by: java.lang.AssertionError
 at com.hydrologis.polymap.geopaparazzi.catalog.GPServiceInfo.<init>(GPServiceInfo.java:71)
 at com.hydrologis.polymap.geopaparazzi.catalog.GPServiceResolver.resolve(GPServiceResolver.java:47)
 at org.polymap.p4.catalog.AllResolver.lambda$3(AllResolver.java:223)
 at java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1590)
 at org.polymap.core.runtime.JobExecutor$2.runWithException(JobExecutor.java:96)
 ... 7 more

**Comment by fb71** [comment]
Pass SqliteDB via user data of every feature.

**Comment by fb71** [comment]
Das 2. Proiekt gibt noch Probleme (aber andere scheinbar):
org.eclipse.swt.SWTException: Failed to execute runnable (java.lang.NullPointerException)
 at org.eclipse.swt.SWT.error(SWT.java:3645)
 at org.eclipse.swt.SWT.error(SWT.java:3568)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:186)
 at org.eclipse.swt.widgets.Display.runPendingMessages(Display.java:1196)
 at org.eclipse.swt.widgets.Display.safeReadAndDispatch(Display.java:1176)
 at org.eclipse.swt.widgets.Display.readAndDispatch(Display.java:1168)
 at org.polymap.rhei.batik.BatikApplication.createUI(BatikApplication.java:163)
 at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle.createUI(RWTLifeCycle.java:172)
 at org.eclipse.rap.rwt.internal.lifecycle.RWTLifeCycle$UIThreadController.run(RWTLifeCycle.java:284)
 at java.lang.Thread.run(Thread.java:745)
 at org.eclipse.rap.rwt.internal.lifecycle.UIThread.run(UIThread.java:105)
Caused by: java.lang.NullPointerException
 at org.geotools.data.Query.hashCode(Query.java:912)
 at java.util.concurrent.ConcurrentHashMap.computeIfAbsent(ConcurrentHashMap.java:1646)
 at org.polymap.core.runtime.cache.Soft2Cache.get(Soft2Cache.java:143)
 at com.hydrologis.polymap.geopaparazzi.catalog.GPFeatureSource.getBounds(GPFeatureSource.java:97)
 at org.geotools.data.AbstractFeatureSource.getBounds(AbstractFeatureSource.java:288)
 at org.polymap.p4.catalog.PreviewMapDashlet.createFeatureLayer(PreviewMapDashlet.java:312)
 at org.polymap.p4.catalog.PreviewMapDashlet.createMap(PreviewMapDashlet.java:202)
 at org.polymap.p4.catalog.PreviewMapDashlet$1.lambda$0(PreviewMapDashlet.java:161)
 at org.polymap.core.runtime.UIThreadExecutor.run(UIThreadExecutor.java:314)
 at org.eclipse.swt.widgets.RunnableLock.run(RunnableLock.java:38)
 at org.eclipse.swt.widgets.Synchronizer.runAsyncMessages(Synchronizer.java:180)
 ... 8 more
